stages:
  - test

test:
  stage: test
  image: python:3.13
  variables:
    TEST: "true"
    PYTHONUNBUFFERED: "1"
    PYTHONPATH: "${CI_PROJECT_DIR}"
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root
  script:
    - poetry run pytest tests